---
title: "Percent Removal for DBF and Chlorination (Phase 2)"
author: "William Raseman"
date: "9/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
# clear environment
rm(list = ls())

# set working directory
setwd("C:/Users/wraseman/Hazen and Sawyer/Stanford, Benjamin - Loxahatchee DBF Evaluation/Data Analysis - Billy")
# load packages
library(tidyverse)  # ggplot2, dplyr for data wrangling and visualization

# read in percent removal data for DBF
data.dir <- "./data/"
filename <- "pct-rmv_dbf.rds"
data.path <- str_c(data.dir, filename)
dbf.df <- read_rds(path = data.path) 

## print dataframe
print(dbf.df)
```
# Visualize boxplots of percent removal for DBF
## Giardia and Cryptosporidium
```{r}
ggplot(data = filter(dbf.df, Parameter %in% c("Giardia", "Cryptosporidium")), 
              aes(x=Parameter, y=PctRmvFilter)) +
  geom_boxplot() +
  ggtitle("Deep Bed Filter") +
  ylab("Percent Removal")
```

## Turbidity
```{r}
ggplot(data = filter(dbf.df, Parameter == "Turbidity"), 
       aes(x=Parameter, y=PctRmvFilter)) +
  geom_boxplot() +
  ggtitle("Deep Bed Filter") +
  ylab("Percent Removal")
```

## Contaminants of emerging concern (CEC)
```{r}
ggplot(data = filter(dbf.df, !(Parameter %in% c("Giardia", "Cryptosporidium", "Turbidity"))), 
       aes(x=Biodeg, y=PctRmvFilter, color=Sorption)) +
  geom_boxplot() +
  ggtitle("Deep Bed Filter") +
  ylab("Percent Removal")
```

# Visualize filter removal data without negative outliers
```{r}
nonneg.filt <- filter(dbf.df, PctRmvFilter >= 0)
```

## Giardia and Cryptosporidium
```{r}
ggplot(data = filter(nonneg.filt, Parameter %in% c("Giardia", "Cryptosporidium")), 
       aes(x=Parameter, y=PctRmvFilter)) +
  geom_boxplot() +
  ggtitle("Deep Bed Filter", "(Negative values removed)") +
  ylab("Percent Removal")
```

## Turbidity
```{r}
ggplot(data = filter(nonneg.filt, Parameter == "Turbidity"), 
                 aes(x=Parameter, y=PctRmvFilter)) +
  geom_boxplot() +
  ggtitle("Deep Bed Filter", "(Negative values removed)") +
  ylab("Percent Removal")
```

## Contaminants of emerging concern (CEC)
```{r}
ggplot(data = filter(nonneg.filt, !(Parameter %in% c("Giardia", "Cryptosporidium", "Turbidity"))), 
       aes(x=Biodeg, y=PctRmvFilter, color=Sorption)) +
  geom_boxplot() +
  ggtitle("Deep Bed Filter") +
  ylab("Percent Removal")
```

# Visualize boxplots of percent removal for chlorination
```{r}
## plot by chlorine oxidation category
ggplot(data = filter(dbf.df, !(Parameter %in% c("Giardia", "Cryptosporidium", "Turbidity"))), 
       aes(x=ClOxidation, y=PctRmvChlorination, color=ClOxidation)) +
  geom_boxplot() +
  ggtitle("Post-Chlorination after Deep Bed Filter") +
  ylab("Percent Removal")

## plot by chlorine oxidation category for only nonnegative values
nonneg.clox <- filter(dbf.df, PctRmvChlorination >= 0)
ggplot(data = filter(nonneg.clox, !(Parameter %in% c("Giardia", "Cryptosporidium", "Turbidity"))), 
       aes(x=ClOxidation, y=PctRmvChlorination, color=ClOxidation)) +
  geom_boxplot() +
  ggtitle("Post-Chlorination after Deep Bed Filter", "(Negative values removed)") +
  ylab("Percent Removal")
```